### ISSUE TITLE
Support saving credit card for PxPay

### ISSUE THREAD

**Issue by maknz** [thephpleague/omnipay-paymentexpress#1]
It would be great if the PxPay implementation supported setting EnableAddBillCard = 1 when creating an Auth or Purchase request.

The use case is using PxPay to save a credit card at DPS, by providing a BillingId and EnableAddBillCard set to 1. We can then use the BillingId we generated for token billing with both PxPay and PxPost, but my use case is saving the credit card with PxPay (thereby reducing PCI-DSS requirements) and rebilling with PxPost.

More information: http://www.paymentexpress.com/Technical_Resources/Ecommerce_Hosted/PxPay#tokenbilling

**Comment by HipsterJazzbo** [comment]
@adrianmacneil Hey I've done this. Will you accept a PR if I put one together?

**Comment by adrianmacneil** [comment]
Sure. I'm no longer maintaining this, but @kayladnls can take a look.

**Comment by HipsterJazzbo** [comment]
@adrianmacneil @kayladnls Awesome, done. Thanks!

**Comment by HipsterJazzbo** [comment]
@adrianmacneil @kayladnls Given the age of all of the unattended issues on here, can I reasonably assume this package is abandoned? Perhaps I could take it over if it need someone to actually look after it?

**Comment by adrianmacneil** [comment]
That would be great. Keeping individual gateways up to date is hard (especially if your test credentials expire etc) so it helps having people to maintain each one. I don't think I have grant anymore, but if @kayladnls can review your PR and that looks good then can probably add to repo.

**Comment by HipsterJazzbo** [comment]
Sweet!

**Comment by kayladnls** [comment]
Once I get that PR moved in, I'll go ahead and grant you access to this repo to keep it maintained. I really appreciate the offer @HipsterJazzbo thank you!
