### ISSUE TITLE
Switching between UAT and Production endpoints

### ISSUE THREAD

**Issue by mediabeastnz** [thephpleague/omnipay-paymentexpress#23]
Switching between UAT and Production endpoints can only be done at the moment by editing the core code directly.

Need a way to switch:
`protected $endpoint = 'https://sec.paymentexpress.com/pxaccess/pxpay.aspx';`
to
`protected $endpoint = 'https://uat.paymentexpress.com/pxaccess/pxpay.aspx';`

**Comment by eileenmcnaughton** [comment]
Hmm - most processors change endpoints depending on 'testMode' e.g from cybersource


    public function getEndpoint()
    {
        return $this->getTestMode() ? $this->testEndpoint : $this->liveEndpoint;
    }

**Comment by delatbabel** [comment]
Can someone submit a PR for this? I don't have a PxPay account.

**Comment by kielabokkie** [comment]
@delatbabel PR for this is merged
