### ISSUE TITLE
Does this support tokens like Stripe or 2Checkout?

### ISSUE THREAD

**Issue by volomike** [thephpleague/omnipay-paymentexpress#27]
With Stripe or 2Checkout via OmniPay, I can collect credit card info on my website with a token that I receive via Javascript. I then only send the token to my server along with billing/shipping address info (just not credit card info) for processing against Stripe or 2Checkout. This is critical for PCI compliance.

**Comment by delatbabel** [comment]
No I don't believe that the gateway supports this functionality via a JS plugin the way that Stripe does.

I don't believe that it's critical for PCI compliance. It's required if you want to *avoid* having to have PCI compliance but if you have PCI compliance then you should not require this functionality.

**Comment by eileenmcnaughton** [comment]
The pxPost gateway collects credit card details, but the pxPay gateway is offsite & is by definition compliant (I presume you refer to the former)
