### ISSUE TITLE
V3 compatibility

### ISSUE THREAD

**Issue by garethhallnz** [thephpleague/omnipay-paymentexpress#46]
I am one of the maintainers for the Drupal Commerce implementation of this gateway. We really really need to start using V3 of omnipay. 
The main reason for this is that event-dispatcher:^2.8 and Guzzle 3 requirement prevents us from installing that latest Drupal versions.

Here is a little more details about the issue we are facing: https://www.drupal.org/project/commerce_dps/issues/2934276

Considering that Ominpay core (V3) is in beta; might I suggest we get a v3 branch too?
I have already upgraded this code to work with V3 core see: https://github.com/garethhallnz/omnipay-paymentexpress/tree/omnipay-v3

Note: While all the tests are passing I have not actually done a real live test yet.

I'll make a pull request once the branch is created.

Thanks

**Comment by barryvdh** [comment]
I branched off the 2.x version. You can create a PR for 3.x to the master branch. Thank you!

**Comment by barryvdh** [comment]
Please make a full PR against the master branch. W
