### ISSUE TITLE
Issue patch release with fix for issue #50

### ISSUE THREAD

**Issue by hchokshi** [thephpleague/omnipay-paymentexpress#52]
PR #51 was merged, which contains a fix for issue #50. Can the maintainers please issue a patch release containing this fix?

**Comment by mikeybeck** [comment]
@hchokshi  the same edit from PR #51 needs to be applied to PxPostGateway.php in order to fully resolve issue #50.  
I'll make a PR for this later tonight, unless you're able to do so earlier.

**Comment by mikeybeck** [comment]
I've opened PR #53 which removes the Guzzle dependency from the PxPost gateway.

**Comment by hchokshi** [comment]
Ahh thanks for that @mikeybeck. Hopefully gets merged and released soon. Didn't notice earlier as all the tests passed without changing this one. Might be a test coverage issue there?

**Comment by hchokshi** [comment]
@barryvdh can we please get a semver tagged release with all the HTTP client fixes now merged? Thanks :)

**Comment by barryvdh** [comment]
Yes tagged v3.0.1
